# Generated by Django 4.2.13 on 2026-04-23 17:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Course Code"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Course Title"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "syllabus",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="syllabi/",
                        verbose_name="Syllabus (PDF)",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        default="2025-2026", max_length=20, verbose_name="Academic Year"
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("Fall", "Fall"),
                            ("Spring", "Spring"),
                            ("Summer", "Summer"),
                        ],
                        max_length=10,
                        verbose_name="Semester",
                    ),
                ),
                (
                    "credits",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="Credits",
                    ),
                ),
                (
                    "max_students",
                    models.PositiveSmallIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(500),
                        ],
                        verbose_name="Max Students",
                    ),
                ),
                (
                    "schedule_days",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Mon, Wed, Fri",
                        max_length=100,
                        verbose_name="Schedule Days",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="Start Time"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="End Time"),
                ),
                (
                    "room",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Room / Location"
                    ),
                ),
                (
                    "delivery_mode",
                    models.CharField(
                        choices=[
                            ("in_person", "In Person"),
                            ("online", "Online"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="in_person",
                        max_length=20,
                        verbose_name="Delivery Mode",
                    ),
                ),
                (
                    "meeting_link",
                    models.URLField(blank=True, verbose_name="Online Meeting Link"),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Course Start Date"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Course End Date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to="accounts.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        limit_choices_to={"role": "professor"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="taught_courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Professor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "db_table": "courses",
                "ordering": ["academic_year", "semester", "course_code"],
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Title")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("assignment", "Assignment"),
                            ("exam", "Exam"),
                            ("grade", "Grade Release"),
                            ("schedule", "Schedule Change"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="Pinned"),
                ),
                (
                    "send_email",
                    models.BooleanField(
                        default=False,
                        help_text="Notify enrolled students via email",
                        verbose_name="Send Email Notification",
                    ),
                ),
                (
                    "publish_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Publish At"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expires At"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
                "db_table": "announcements",
                "ordering": ["-is_pinned", "-publish_at"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("dropped", "Dropped"),
                            ("completed", "Completed"),
                            ("waitlisted", "Waitlisted"),
                            ("withdrawn", "Withdrawn"),
                            ("failed", "Failed"),
                        ],
                        default="enrolled",
                        max_length=20,
                        verbose_name="Enrollment Status",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Enrollment Date",
                    ),
                ),
                (
                    "drop_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Drop Date"
                    ),
                ),
                (
                    "completion_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completion Date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="accounts.studentprofile",
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enrollment",
                "verbose_name_plural": "Enrollments",
                "db_table": "enrollments",
                "ordering": ["-enrollment_date"],
                "indexes": [
                    models.Index(
                        fields=["student", "status"],
                        name="enrollments_student_929bef_idx",
                    ),
                    models.Index(
                        fields=["course", "status"],
                        name="enrollments_course__931283_idx",
                    ),
                ],
                "unique_together": {("student", "course")},
            },
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["course_code"], name="courses_course__5da9ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["professor"], name="courses_profess_2ee815_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["status"], name="courses_status_67f368_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["academic_year", "semester"], name="courses_academi_e95e89_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("course_code", "academic_year", "semester")},
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["course", "-publish_at"], name="announcemen_course__17a4be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["priority"], name="announcemen_priorit_370592_idx"
            ),
        ),
    ]
