# Generated by Django 4.2.13 on 2026-04-09 03:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numeric_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Numeric Score (%)",
                    ),
                ),
                (
                    "letter_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A", "A"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B", "B"),
                            ("B-", "B-"),
                            ("C+", "C+"),
                            ("C", "C"),
                            ("C-", "C-"),
                            ("D+", "D+"),
                            ("D", "D"),
                            ("D-", "D-"),
                            ("F", "F"),
                            ("W", "W — Withdrawn"),
                            ("I", "I — Incomplete"),
                            ("P", "P — Pass"),
                            ("NP", "NP — No Pass"),
                        ],
                        max_length=3,
                        verbose_name="Letter Grade",
                    ),
                ),
                (
                    "grade_points",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=4,
                        verbose_name="GPA Points",
                    ),
                ),
                (
                    "midterm_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Midterm Score",
                    ),
                ),
                (
                    "final_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Final Exam Score",
                    ),
                ),
                (
                    "assignment_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Assignment Score",
                    ),
                ),
                (
                    "quiz_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Quiz Score",
                    ),
                ),
                (
                    "project_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Project Score",
                    ),
                ),
                (
                    "participation_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Participation Score",
                    ),
                ),
                (
                    "is_finalized",
                    models.BooleanField(default=False, verbose_name="Finalized"),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, verbose_name="Professor Remarks"),
                ),
                (
                    "graded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Graded At"
                    ),
                ),
                (
                    "finalized_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finalized At"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade",
                        to="courses.enrollment",
                        verbose_name="Enrollment",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "professor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grades_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Graded By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade",
                "verbose_name_plural": "Grades",
                "db_table": "grades",
                "ordering": ["-graded_at"],
            },
        ),
        migrations.CreateModel(
            name="GradeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_numeric_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "new_numeric_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("old_letter_grade", models.CharField(blank=True, max_length=3)),
                ("new_letter_grade", models.CharField(blank=True, max_length=3)),
                (
                    "reason",
                    models.TextField(blank=True, verbose_name="Reason for Change"),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed By",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="grades.grade",
                        verbose_name="Grade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade History",
                "verbose_name_plural": "Grade History",
                "db_table": "grade_history",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="GradeComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Component Name"),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("midterm", "Midterm Exam"),
                            ("final", "Final Exam"),
                            ("quiz", "Quiz"),
                            ("assignment", "Assignment"),
                            ("project", "Project"),
                            ("lab", "Lab"),
                            ("participation", "Participation"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage weight toward final grade (all weights must sum to 100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Weight (%)",
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Max Score",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_components",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade Component",
                "verbose_name_plural": "Grade Components",
                "db_table": "grade_components",
                "ordering": ["course", "order", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(fields=["enrollment"], name="grades_enrollm_1d9462_idx"),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["letter_grade"], name="grades_letter__60cd46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["is_finalized"], name="grades_is_fina_b1e9b1_idx"
            ),
        ),
    ]
