# Generated by Django 4.2.13 on 2026-04-09 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_sessions", models.PositiveIntegerField(default=0)),
                ("present_count", models.PositiveIntegerField(default=0)),
                ("absent_count", models.PositiveIntegerField(default=0)),
                ("late_count", models.PositiveIntegerField(default=0)),
                ("excused_count", models.PositiveIntegerField(default=0)),
                ("remote_count", models.PositiveIntegerField(default=0)),
                (
                    "attendance_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_summary",
                        to="courses.enrollment",
                        verbose_name="Enrollment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Summary",
                "verbose_name_plural": "Attendance Summaries",
                "db_table": "attendance_summaries",
            },
        ),
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Session Date")),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("lecture", "Lecture"),
                            ("lab", "Lab"),
                            ("tutorial", "Tutorial"),
                            ("exam", "Exam"),
                            ("other", "Other"),
                        ],
                        default="lecture",
                        max_length=20,
                        verbose_name="Session Type",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        blank=True,
                        help_text="What was covered in this session?",
                        max_length=300,
                        verbose_name="Topic Covered",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Session Notes")),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Lock prevents further edits to attendance records",
                        verbose_name="Locked",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sessions",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Session",
                "verbose_name_plural": "Attendance Sessions",
                "db_table": "attendance_sessions",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("excused", "Excused Absence"),
                            ("remote", "Attended Remotely"),
                        ],
                        default="absent",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "arrival_time",
                    models.TimeField(
                        blank=True,
                        help_text="Only for late arrivals",
                        null=True,
                        verbose_name="Arrival Time",
                    ),
                ),
                (
                    "excuse_reason",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Excuse Reason"
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=500, verbose_name="Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="courses.enrollment",
                        verbose_name="Enrollment",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_attendance",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Marked By",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="attendance.attendancesession",
                        verbose_name="Session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "db_table": "attendance_records",
                "ordering": ["session", "enrollment__student__student_id"],
            },
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["course", "-date"], name="attendance__course__87b9c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(fields=["date"], name="attendance__date_3a1d74_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="attendancesession",
            unique_together={("course", "date", "session_type")},
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["session", "status"], name="attendance__session_523367_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["enrollment"], name="attendance__enrollm_5cbedc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("session", "enrollment")},
        ),
    ]
