# Generated by Django 4.2.13 on 2026-04-23 17:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
        ("accounts", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Title")),
                (
                    "description",
                    models.TextField(verbose_name="Description / Instructions"),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("homework", "Homework"),
                            ("quiz", "Quiz"),
                            ("midterm", "Midterm Exam"),
                            ("final", "Final Exam"),
                            ("project", "Project"),
                            ("lab", "Lab Report"),
                            ("essay", "Essay"),
                            ("presentation", "Presentation"),
                            ("other", "Other"),
                        ],
                        default="homework",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("closed", "Closed"),
                            ("graded", "Graded"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Maximum Score",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Weight in Final Grade (%)",
                    ),
                ),
                (
                    "assigned_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Assigned Date"
                    ),
                ),
                ("due_date", models.DateTimeField(verbose_name="Due Date")),
                (
                    "late_submission_allowed",
                    models.BooleanField(
                        default=False, verbose_name="Allow Late Submissions"
                    ),
                ),
                (
                    "late_penalty_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Percentage deducted for late submissions",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Late Penalty (%)",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="assignments/files/",
                        verbose_name="Attachment",
                    ),
                ),
                (
                    "reference_url",
                    models.URLField(blank=True, verbose_name="Reference URL"),
                ),
                (
                    "allow_resubmission",
                    models.BooleanField(
                        default=False, verbose_name="Allow Resubmission"
                    ),
                ),
                (
                    "max_submissions",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Max Submissions Allowed",
                    ),
                ),
                (
                    "submission_format",
                    models.CharField(
                        blank=True,
                        help_text="e.g. PDF, DOCX, ZIP",
                        max_length=200,
                        verbose_name="Accepted File Formats",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "professor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
                "db_table": "assignments",
                "ordering": ["due_date", "course"],
            },
        ),
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_text",
                    models.TextField(
                        blank=True,
                        help_text="Written response / answer",
                        verbose_name="Submission Text",
                    ),
                ),
                (
                    "submission_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="submissions/files/%Y/%m/",
                        verbose_name="Submitted File",
                    ),
                ),
                (
                    "submission_url",
                    models.URLField(
                        blank=True, verbose_name="Submission URL (e.g. GitHub)"
                    ),
                ),
                (
                    "submission_number",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Submission Number"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Saved as Draft"),
                            ("submitted", "Submitted"),
                            ("late", "Submitted Late"),
                            ("resubmitted", "Resubmitted"),
                            ("graded", "Graded"),
                            ("returned", "Returned for Revision"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Submitted At"
                    ),
                ),
                (
                    "is_late",
                    models.BooleanField(default=False, verbose_name="Late Submission"),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Score",
                    ),
                ),
                (
                    "adjusted_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Adjusted Score (after penalties)",
                    ),
                ),
                (
                    "is_graded",
                    models.BooleanField(default=False, verbose_name="Graded"),
                ),
                (
                    "graded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Graded At"
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, verbose_name="Instructor Feedback"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="assignments.assignment",
                        verbose_name="Assignment",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Graded By",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="accounts.studentprofile",
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment Submission",
                "verbose_name_plural": "Assignment Submissions",
                "db_table": "assignment_submissions",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Comment")),
                (
                    "is_private",
                    models.BooleanField(
                        default=False,
                        help_text="Private comments are only visible to professors",
                        verbose_name="Private",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="assignments.submissioncomment",
                        verbose_name="Reply To",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="assignments.assignmentsubmission",
                        verbose_name="Submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission Comment",
                "verbose_name_plural": "Submission Comments",
                "db_table": "submission_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="assignmentsubmission",
            index=models.Index(
                fields=["assignment", "student"], name="assignment__assignm_c9693f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignmentsubmission",
            index=models.Index(
                fields=["is_graded"], name="assignment__is_grad_b8be5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignmentsubmission",
            index=models.Index(
                fields=["submitted_at"], name="assignment__submitt_040795_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["course", "status"], name="assignments_course__faa027_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["due_date"], name="assignments_due_dat_708d3b_idx"
            ),
        ),
    ]
